// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ifood/leakspok/analyzer (interfaces: WorkerPool)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_worker_pool.go -package=analyzermock github.com/ifood/leakspok/analyzer WorkerPool
//

// Package analyzermock is a generated GoMock package.
package analyzermock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkerPool is a mock of WorkerPool interface.
type MockWorkerPool struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerPoolMockRecorder
}

// MockWorkerPoolMockRecorder is the mock recorder for MockWorkerPool.
type MockWorkerPoolMockRecorder struct {
	mock *MockWorkerPool
}

// NewMockWorkerPool creates a new mock instance.
func NewMockWorkerPool(ctrl *gomock.Controller) *MockWorkerPool {
	mock := &MockWorkerPool{ctrl: ctrl}
	mock.recorder = &MockWorkerPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerPool) EXPECT() *MockWorkerPoolMockRecorder {
	return m.recorder
}

// ReleaseContext mocks base method.
func (m *MockWorkerPool) ReleaseContext(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseContext", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseContext indicates an expected call of ReleaseContext.
func (mr *MockWorkerPoolMockRecorder) ReleaseContext(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseContext", reflect.TypeOf((*MockWorkerPool)(nil).ReleaseContext), arg0)
}

// Submit mocks base method.
func (m *MockWorkerPool) Submit(arg0 func()) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Submit indicates an expected call of Submit.
func (mr *MockWorkerPoolMockRecorder) Submit(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockWorkerPool)(nil).Submit), arg0)
}
