// Code generated by MockGen. DO NOT EDIT.
// Source: rules.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_rules.go -package=analyzermock -source=rules.go
//

// Package analyzermock is a generated GoMock package.
package analyzermock

import (
	context "context"
	reflect "reflect"

	pattern "github.com/ifood/leakspok/pattern"
	gomock "go.uber.org/mock/gomock"
)

// MockMatcher is a mock of Matcher interface.
type MockMatcher struct {
	ctrl     *gomock.Controller
	recorder *MockMatcherMockRecorder
	isgomock struct{}
}

// MockMatcherMockRecorder is the mock recorder for MockMatcher.
type MockMatcherMockRecorder struct {
	mock *MockMatcher
}

// NewMockMatcher creates a new mock instance.
func NewMockMatcher(ctrl *gomock.Controller) *MockMatcher {
	mock := &MockMatcher{ctrl: ctrl}
	mock.recorder = &MockMatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatcher) EXPECT() *MockMatcherMockRecorder {
	return m.recorder
}

// Entity mocks base method.
func (m *MockMatcher) Entity() pattern.Entity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Entity")
	ret0, _ := ret[0].(pattern.Entity)
	return ret0
}

// Entity indicates an expected call of Entity.
func (mr *MockMatcherMockRecorder) Entity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Entity", reflect.TypeOf((*MockMatcher)(nil).Entity))
}

// Match mocks base method.
func (m *MockMatcher) Match(ctx context.Context, input []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Match", ctx, input)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Match indicates an expected call of Match.
func (mr *MockMatcherMockRecorder) Match(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockMatcher)(nil).Match), ctx, input)
}
