// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Prosus-Cyber-Xchange/leakspok/analyzer/cache (interfaces: CacheStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_cache_store.go -package=cachemock github.com/Prosus-Cyber-Xchange/leakspok/analyzer/cache CacheStore
//

// Package cachemock is a generated GoMock package.
package cachemock

import (
	context "context"
	reflect "reflect"

	pattern "github.com/Prosus-Cyber-Xchange/leakspok/pattern"
	gomock "go.uber.org/mock/gomock"
)

// MockCacheStore is a mock of CacheStore interface.
type MockCacheStore struct {
	ctrl     *gomock.Controller
	recorder *MockCacheStoreMockRecorder
	isgomock struct{}
}

// MockCacheStoreMockRecorder is the mock recorder for MockCacheStore.
type MockCacheStoreMockRecorder struct {
	mock *MockCacheStore
}

// NewMockCacheStore creates a new mock instance.
func NewMockCacheStore(ctrl *gomock.Controller) *MockCacheStore {
	mock := &MockCacheStore{ctrl: ctrl}
	mock.recorder = &MockCacheStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheStore) EXPECT() *MockCacheStoreMockRecorder {
	return m.recorder
}

// GetMatch mocks base method.
func (m *MockCacheStore) GetMatch(ctx context.Context, entity pattern.Entity, data []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatch", ctx, entity, data)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatch indicates an expected call of GetMatch.
func (mr *MockCacheStoreMockRecorder) GetMatch(ctx, entity, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatch", reflect.TypeOf((*MockCacheStore)(nil).GetMatch), ctx, entity, data)
}

// SaveMatch mocks base method.
func (m *MockCacheStore) SaveMatch(ctx context.Context, entity pattern.Entity, data []byte, matched bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMatch", ctx, entity, data, matched)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMatch indicates an expected call of SaveMatch.
func (mr *MockCacheStoreMockRecorder) SaveMatch(ctx, entity, data, matched any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMatch", reflect.TypeOf((*MockCacheStore)(nil).SaveMatch), ctx, entity, data, matched)
}
